### ISSUE TITLE
Change Password error

### ISSUE THREAD

**Issue by LemaireJean-Baptiste** [2karis/Php-login-and-Registration-System#1]
Hello you made a mistake in your authController.php files. 
Indeed, it returns an error when you try to change password. It's because you try to pass $password in the update function while the form you set up in your view return password_old and password_new. So $password is null. You only need to modify the value you pass in your update function.

`     public function postChangePassword($request, $response){
        $validation = $this->validator->validate($request, [
                'password_old'=>v::noWhitespace()->notEmpty()->MatchesPassword($this->auth->user()->password),
                'password_new'=> v::noWhitespace()->notEmpty(),
            ]);
        if($this->validator->failed()){
            return $response->withRedirect($this->router->pathFor('auth.password.change'));
        }
        $this->auth->user->update([
            'password'=>password_hash($password, PASSWORD_DEFAULT)
        ]);
        $this->flash->addMessage('info', 'Your password was Changed.');
        return $response->withRedirect($this->router->pathFor('home'));
    }`

By the way, thank you for the sharing

**Comment by 2karis** [comment]
i had noticed the issue some time back but i forgot to fix it. thank you for notifying me. it should be fixed now
